### ISSUE TITLE
not working with selfsign certificate

### ISSUE THREAD

**Issue by atlanticfirst** [Utazukin/Ichaival#52]
This app currently does not support self-signed certificates. Will you consider adding support for self-signed certificates in the future?

**Comment by Utazukin** [comment]
I'm not able to test locally, but I believe as long as the certificates have been added to the device, they should be working now.

**Comment by atlanticfirst** [comment]
It's still not working，shows 'server version unsupported' now😂

**Comment by atlanticfirst** [comment]
F-Droid just updated to version 1.8......After the update, it opens normally. Sorry, I didn't check the version on F-Droid before
